### ISSUE TITLE
"The elm.json for elm-community/list-extra 1.0.0 got corrupted somehow"

### ISSUE THREAD

**Issue by justgage** [jfmengels/review-common#1]
When I try to install it I get this error

```
λ ~/sandbox/code-review-frontend/ master* elm install jfmengels/review-common                                      
-- CORRUPT JSON ----------------------------------------------------------------

The elm.json for elm-community/list-extra 1.0.0 got corrupted somehow.

I removed it from my file cache, so if it was some transient error it should be
fixed if you try the same thing again. Please report this if it seems like an
Elm problem though!
```

This package seems very old, so I'm not sure why this is being used. Maybe a dep of a dep?

**Comment by jfmengels** [comment]
Hey @justgage :wave: 

You're right, it is really old. As in it is not compatible with Elm 0.19 (but Elm 0.17).

`elm-community/list-extra` is not part of this package's dependencies (be it direct or indirect), so I doubt the issue lies in this package.

My guess is you already had an incorrect `elm.json` file with some very outdated dependencies, or maybe ones added by hand.
I recommend re-initializing your `elm.json` from scratch and seeing which dependency has a problem being added.

Let me know how it goes!

**Comment by jfmengels** [comment]
I'll close this issue because there isn't much I can do, but let me know if you run into this again.
